name: typed_prefs
description:
  'A code generator for Flutter that creates type-safe wrappers around
  SharedPreferences and FlutterSecureStorage, allowing developers to define
  their preferences in a structured way and access them with strong typing.'
version: 1.1.0
repository: https://github.com/vartec-chs/typed_prefs_flutter
homepage: https://github.com/vartec-chs/typed_prefs_flutter

environment:
  sdk: ^3.11.1
  flutter: '>=1.17.0'

dependencies:
  analyzer: ^10.0.0
  build: ^4.0.4
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  source_gen: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.12.2

flutter:
